name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ› ï¸ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ“¥ Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export BUN_INSTALL="$HOME/.bun"' >> $GITHUB_ENV
          echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $GITHUB_ENV

      - name: ğŸ“¦ Install dependencies with bun
        run: bun install --frozen-lockfile
        env:
          BUN_INSTALL: ${{ env.BUN_INSTALL }}
          PATH: ${{ env.PATH }}

      - name: ğŸ” Run linter with bun
        run: bun lint
        env:
          BUN_INSTALL: ${{ env.BUN_INSTALL }}
          PATH: ${{ env.PATH }}

      - name: ğŸ’¾ Commit linter fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Linter fixes"
