name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:latest

    steps:
      - name: ğŸ› ï¸ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ“¦ Install dependencies with bun
        run: bun install --frozen-lockfile

      - name: ğŸ” Run linter with bun
        run: bun lint

      - name: ğŸ’¾ Commit linter fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Linter fixes"
          branch: ${{ github.head_ref }}
          file_pattern: "."
        continue-on-error: true
